version: '3'
services:
  web:
    build: ./web
    env_file:
     - ./.env
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis
    stdin_open: true
    tty: true
    restart: on-failure
  redis:
    build: ./redis
    network_mode: host
  #db-writer:
