version: '3'
services:
  redis:
    container_name: redis
    build: ./redis
    network_mode: host
 
  mqtt-server:
    container_name: mqtt-server
    build: ./mqtt-server
    network_mode: host

  mqtt-subscriber:
    container_name: mqtt-subscriber
    build: ./mqtt-subscriber
    env_file:
     - ./.env
    network_mode: host
    depends_on:
      - mqtt-server
      - redis

  web:
    container_name: web
    build: ./web
    env_file:
     - ./.env
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis
    stdin_open: true
   #tty: true
   #restart: on-failure

 #db-writer:
